name: Publish to crates.io

on:
  workflow_dispatch: {}
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      # build
      - uses: actions/checkout@v4
      - name: install llvm tools preview
        run: rustup component add llvm-tools-preview
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --all-features

      # test
      - name: Run tests
        run: LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose --all-features

      # publish
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_TOKEN }}
          check-repo: false
